### PR TITLE
Add a subslice function for Bytes (#198)

### PR DESCRIPTION
**Pull request by federicomenaquintero**

### CODE REVIEW

**Comment by carllerche** [comment]
Sorry for letting this hang. I will try to up prioritize it.

The implementation is good. The name is bugging me. I would like it to match the pattern of the others. So, I would like a name like:

`slice_???`

Except, I can't think of anything good :(

Best I could think of is `slice_subset`... but I Don't like that either. Thoughts?

**Comment by carllerche** [comment]
Or, what about `slice_for`?

```rust
let bytes = Bytes::from(&b"012345678"[..]);
let as_slice = bytes.as_ref();
let sub = &as_slice[2..6];
let sub = bytes.slice_for(&sub);
assert_eq!(&sub[..], b"2345");
```

**Comment by carllerche** [comment]
Another (via Ralith in gitter): `slice_ref`

```rust
let bytes = Bytes::from(&b"012345678"[..]);
let as_slice = bytes.as_ref();
let sub = &as_slice[2..6];
let sub = bytes.slice_for(&sub);
assert_eq!(&sub[..], b"2345");
```

**Comment by carllerche** [comment]
I'm like `slice_ref` as it follows the `slice_` pattern and implies that you are slicing using a reference to self.

`bytes.slice_ref(self.as_ref()) == bytes`

**Comment by federicomenaquintero** [comment]
Cool, I'll rebase this and use `slice_ref`.

**Comment by federicomenaquintero** [comment]
I've renamed the function to `slice_ref()` and the `sub` argument to `subset`.  Also changed the test names to make it more clear what they are doing.

**Comment by carllerche** [comment]
Thanks for sticking with it 👍

**Comment by carllerche** [comment]
I'm going to rebase the PR against the `0.4.x` branch.

**Comment by carllerche** [comment]
CI hung for some reason...

**Comment by federicomenaquintero** [comment]
Yay, thanks!

**Pull request merged**
