### PR TITLE
Optimize Bytes::slice(n, n)

### PR DESCRIPTION
**Pull request by stepancheg**
Return empty `Bytes` object

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. It would be nice to have an associated benchmark to show the advantage (though, I think that it is likely to be an improvement).

**Comment by stepancheg** [comment]
I've added a simple benchmark. It it enough or more benchmarks needed?

**Comment by stepancheg** [comment]
In that benchmark difference is

```
55 ns/iter (+/- 1) # before this patch
17 ns/iter (+/- 5) # with this patch
```

**Comment by carllerche** [comment]
Looks good, maybe add a slice fn that doesn't hit the empty case to see if there is a negative impact?

(Mostly, since you are willing I'm getting you to write some benchmarks which will help guard against future perf regressions 👍 )

**Comment by stepancheg** [comment]
Added a bench for non-empty slice. No difference in that case.

**Comment by stepancheg** [comment]
```
25,058 ns/iter (+/- 1,099) # before this patch
25,072 ns/iter (+/- 1,593) # with this patch
```

(variance is high)

**Comment by carllerche** [comment]
Thanks.

**Pull request merged**
